### ISSUE TITLE
It's unfair for Scala

### ISSUE THREAD

**Issue by DieterLi** [rskupnik/pet-clinic-jvm#4]
I don't think it's the right way to use Scala, just like trying to squeeze a big foot into a small shoes.

Scala has a complete ecosystem, fulfilling the same purpose as Spring does, not just a plain language level transforming. 

Scala use case class for entity in most cases, and trait to enhance the functions. 

Only follow the Scala way, then the gorgeous java IL will be compiled. 

In this repo, it cuts off Scala's legs and let it run.

**Comment by rskupnik** [comment]
I explicitly mention that there are dedicated frameworks for doing web in Scala (Play Framework is mentioned in the text by name) and that I consider Kotlin better only in this particular, precise use case (which is using Spring Boot with a JVM language that is not Java). The Scala implementation is not perfect, as also mentioned in the text, but I'm exploring a few improvement options - they don't change the fact Kotlin was much easier to get working, though.
